config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    # resources :ingredient

    resources :cocktails do
      resources :doses, only: [:new, :create]
    end
    resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # before_action :cocktail_params, only [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save!
    redirect_to cocktail_path(@cocktail)
  end

  def edit
  end

  def destroy
    @cocktail.destroy
    # DELETE FROM restaurants WHERE id = id
    # UPDATE restaurants SET destroyed_at = Time.now WHERE id = id
    redirect_to cocktails_url, notice: 'Cocktail was successfully deleted.'
  end

  private
    def cocktail_params
      params.require(:cocktail).permit(:name)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(id: @cocktail.id)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail_id
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail), notice: 'Dose was successfully deleted.'
  end


  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/controllers/ingredient_controller.rb
class IngredientController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for [ @cocktail ] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <!-- <div class="form-actions">
    <%#= f.button :submit %>
  </div> -->

  <%= f.submit "Confirm", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>




 <div class="container">
  <!-- bannder -->
  <div class="banner">
    <h1>Cocktails</h1>
    <p>Order. Drink. Drunk. Cheers.</p>
  </div>
  <% @cocktails.each do |cocktail| %>
    <div class="card-trip">
      <img src="https://images.unsplash.com/photo-1596097092650-730ba9475ad5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=600&q=60">
      <div class="card-trip-infos">
        <h2> <%= link_to cocktail.name, cocktail %></h2>
        <p><%= link_to 'Edit', edit_cocktail_path(cocktail)%></p>
      </div>
    </div>
  <% end %>
</div>




<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back to menu', cocktails_path %>

app/views/cocktails/show.html.erb
<!-- <p>
  <%#= @cocktail.name %>
</p> -->


<div class="banner" style="background color: white">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>

<div>
   <% @cocktail.doses.each do |dose| %>
      <tr>
        <td><%= dose.description %></td>
        <td><%= dose.ingredient.name %></td>
      <%= link_to 'Remove', dose_path(dose), method: :delete %>
      </tr>
  <% end %>
</div>

<%= link_to 'Add doses', new_cocktail_dose_path(@cocktail) %>
<%= link_to 'Back to main page ', cocktails_path %>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose ] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">



  </head>

  <body>




    <%= yield %>
  </body>
</html>